columns:
  CreditScore: int64
  Geography: object
  Gender: object
  Age: float64
  Tenure: int64
  Balance: float64
  NumOfProducts: int64
  HasCrCard: float64
  IsActiveMember: float64
  EstimatedSalary: float64
  Exited: int64
numerical_columns:
- RowNumber
- CustomerId
- CreditScore
- Age
- Tenure
- Balance
- NumOfProducts
- HasCrCard
- IsActiveMember
- EstimatedSalary
- Exited
validations:
  Geography:
    allowed_categories:
    - France
    - Spain
    - Germany
  Age:
    min_value: 0
  Gender:
    allowed_categories:
    - Female
    - Male