name: Train & Register Model

on:
  push:               # runs on every push to main
    branches: [ main ]
  # schedule:         # or nightly
  #   - cron: '0 2 * * *'

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with: { python-version: '3.10' }

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Install package (editable)
        run: pip install -e .

      - name: Configure Git and DVC
        run: |
          git config --global user.email "kasun.com"
          git config --global user.name "Your Name"
          dvc remote modify origin auth basic
          dvc remote modify origin user $MLFLOW_TRACKING_USERNAME
          dvc remote modify origin password $DAGSHUB_TOKEN



      - name: Train & register model
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          export MLFLOW_TRACKING_URI=https://dagshub.com/kazwij/customerchurn.mlflow
          export MLFLOW_TRACKING_USERNAME=kazwij
          export MLFLOW_TRACKING_PASSWORD=$DAGSHUB_TOKEN
          echo "Tracking URI: $MLFLOW_TRACKING_URI"
          python customerchurn/pipeline/training_pipeline.py

